name: Deploy Firebase Functions

on:
  push:
    branches:
      - main # Or whatever your main branch is called

jobs:
  deploy:
    name: Build and Deploy Functions
    runs-on: ubuntu-latest # Use a standard Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js version 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies for Functions
        # This runs 'npm install' inside the 'functions' directory
        run: npm --prefix functions install

      - name: Build Functions TypeScript
        # This runs 'npm run build' inside the 'functions' directory
        run: npm --prefix functions run build

      - name: Install Firebase CLI
        # This installs the firebase-tools package globally on the runner
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        # This runs the deploy command using the FIREBASE_TOKEN secret you created
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"